"""Deterministic TrustForge kernel contracts.

This package is intentionally dependency-free.  Runtime providers, storage,
application schemas, and orchestration belong outside this boundary.
"""

from .contracts import (
    KERNEL_CONTRACT_VERSION,
    JsonValue,
    KernelClaim,
    KernelDocument,
    KernelInput,
    KernelOutput,
    KernelReputationTrace,
    KernelScoredClaim,
    UnsupportedKernelContractVersion,
    require_supported_contract_version,
)
from .aggregation import (
    FIXED_HEURISTIC_TABLE,
    FIXED_HEURISTIC_VERSION,
    ISOTONIC_VERSION,
    SUPPORTED_CALIBRATION_MODEL_VERSIONS,
    aggregate_scored_claims,
)
from .corroboration import (
    CorroborationClaim,
    CorroborationResult,
    DOMAIN_STOP,
    StanceLabel,
    StancePair,
    canonical_source,
    corroborate,
    directional_word_polarities,
)
from .dawid_skene import LABELS, N_LABELS, em_source_reliability
from .scoring import (
    DEFAULT_HALF_LIVES,
    DEFAULT_SCORE_WEIGHTS,
    DEFAULT_SOURCE_REPUTATIONS,
    corroboration_score,
    interpolate_calibration,
    manipulation_flags,
    manipulation_hits,
    manipulation_penalty,
    recency_decay,
    reputation_floor,
    score_claim,
    source_reputation,
    stable_sigmoid,
)

__all__ = [
    "FIXED_HEURISTIC_TABLE",
    "FIXED_HEURISTIC_VERSION",
    "ISOTONIC_VERSION",
    "SUPPORTED_CALIBRATION_MODEL_VERSIONS",
    "aggregate_scored_claims",
    "KERNEL_CONTRACT_VERSION",
    "JsonValue",
    "KernelClaim",
    "KernelDocument",
    "KernelInput",
    "KernelOutput",
    "KernelReputationTrace",
    "KernelScoredClaim",
    "UnsupportedKernelContractVersion",
    "require_supported_contract_version",
    "CorroborationClaim",
    "CorroborationResult",
    "DOMAIN_STOP",
    "StanceLabel",
    "StancePair",
    "canonical_source",
    "corroborate",
    "directional_word_polarities",
    "LABELS",
    "N_LABELS",
    "em_source_reliability",
    "DEFAULT_HALF_LIVES",
    "DEFAULT_SCORE_WEIGHTS",
    "DEFAULT_SOURCE_REPUTATIONS",
    "corroboration_score",
    "interpolate_calibration",
    "manipulation_flags",
    "manipulation_hits",
    "manipulation_penalty",
    "recency_decay",
    "reputation_floor",
    "score_claim",
    "source_reputation",
    "stable_sigmoid",
]
