"""Deterministic TrustForge kernel contracts.

This package is intentionally dependency-free.  Runtime providers, storage,
application schemas, and orchestration belong outside this boundary.
"""

from .contracts import (
    KERNEL_CONTRACT_VERSION,
    JsonValue,
    KernelClaim,
    KernelDocument,
    KernelInput,
    KernelOutput,
    KernelReputationTrace,
    KernelScoredClaim,
    UnsupportedKernelContractVersion,
    require_supported_contract_version,
)
from .corroboration import (
    CorroborationClaim,
    CorroborationResult,
    DOMAIN_STOP,
    StanceLabel,
    StancePair,
    canonical_source,
    corroborate,
    directional_word_polarities,
)
from .dawid_skene import LABELS, N_LABELS, em_source_reliability
from .scoring import (
    CONTRARIAN_LIMIT,
    DEFAULT_CALIBRATION_TABLE,
    DEFAULT_HALF_LIVES,
    DEFAULT_SCORE_WEIGHTS,
    DEFAULT_SOURCE_REPUTATIONS,
    DEFAULT_STRENGTH_WEIGHTS,
    INDEPENDENT_SOURCE_SATURATION,
    KIND_DIVERSITY_SATURATION,
    SUPPORTING_LIMIT,
    aggregate_scored_claims,
    corroboration_score,
    evidence_strength,
    interpolate_calibration,
    manipulation_flags,
    manipulation_hits,
    manipulation_penalty,
    recency_decay,
    reputation_floor,
    run_kernel,
    score_claim,
    source_reputation,
    stable_sigmoid,
)

__all__ = [
    "KERNEL_CONTRACT_VERSION",
    "JsonValue",
    "KernelClaim",
    "KernelDocument",
    "KernelInput",
    "KernelOutput",
    "KernelReputationTrace",
    "KernelScoredClaim",
    "UnsupportedKernelContractVersion",
    "require_supported_contract_version",
    "CorroborationClaim",
    "CorroborationResult",
    "DOMAIN_STOP",
    "StanceLabel",
    "StancePair",
    "canonical_source",
    "corroborate",
    "directional_word_polarities",
    "LABELS",
    "N_LABELS",
    "em_source_reliability",
    "CONTRARIAN_LIMIT",
    "DEFAULT_CALIBRATION_TABLE",
    "DEFAULT_HALF_LIVES",
    "DEFAULT_SCORE_WEIGHTS",
    "DEFAULT_SOURCE_REPUTATIONS",
    "DEFAULT_STRENGTH_WEIGHTS",
    "INDEPENDENT_SOURCE_SATURATION",
    "KIND_DIVERSITY_SATURATION",
    "SUPPORTING_LIMIT",
    "aggregate_scored_claims",
    "corroboration_score",
    "evidence_strength",
    "interpolate_calibration",
    "manipulation_flags",
    "manipulation_hits",
    "manipulation_penalty",
    "recency_decay",
    "reputation_floor",
    "run_kernel",
    "score_claim",
    "source_reputation",
    "stable_sigmoid",
]
